<?php
?>
<div class="privacy-wrapper">
<div><h3>Privacy Policy</h3></div>
<div>
<p>Gloobers Global Ltd ("Gloobers", "us" or "we") hereby informs you that our primary target in collecting information is to improve our Platform and Services and enhance users' experience. This Privacy Policy applies only to information that you provide and/or upload to and/or through the Platform. Gloobers may update this Privacy Policy from time to time and at its own discretion. Please review this page from time to time for the latest updates.
As used in this policy, the terms "using" and "processing" information include using cookies on a computer, subjecting the information to statistical or other analysis and using or handling information in any way, including, but not limited to collecting, storing, evaluating, modifying, deleting, using, combining, disclosing and transferring information within our organization or among our affiliates within the United States or internationally.</p>
<h4>Transfer of information</h4>
<p>Your information may be transferred or stored on computer and/or servers located outside your country of residence and where privacy laws may not be as strict and as protective as those in your country of residence. By submitting information to the Platform you agree to the transfer as mentioned here above.</p>
<h4>Personal and Billing Information</h4>
<p>While registering and using the different features of the Platform, we may ask you for personal information. e.g. name, address, email, phone etc. and other information and/or preferences you may upload to your account <b>("Personal Information")</b>. For the purpose of executing transactions through the Platform we may ask for your credit card number and other billing information <b>("Billing Information")</b>. We use your Personal and Billing Information to provide the Service according to the Terms of Use. <p>
<p>You may register to the Platform via our site, application or third party sites where you are a member. Should you register through a third party site, you hereby confirm and warrant that you are allowed to do so without breach of any of the terms and conditions that govern your use of the applicable third party site and without imposing on us any obligations of any kind. You also authorize Gloobers to retrieve, obtain and use your Personal and Billing Information from the applicable third party site. We may use your Personal Information or parts of it in order to improve the Platform's users' experience.</p>
<p>We may also use your Personal Information send newsletters, marketing or promotional materials and other information. If you do not wish to receive such information, please follow the unsubscribe instructions provided in any of the communications or update your "Notifications" information. Please note that we may also send you information related to your use of the Platform and you may not opt out of these notifications.</p>
<h4>Log Information</h4>
<p>When you visit the Platform, as a registered member or non-registered visitor, Gloobers' servers automatically collect information that your browser sends when you log into sites. This log information may include your computer's Internet Protocol address, browser type or the webpage you were visiting before, pages of you visit, the time spent on each page, information you search for, access times and dates and other statistics. We use this information to monitor and analyze the use of our Platform, enhance its functionality, improve its technical administration, increase our visitors' use experience. We may share aggregated information and log information that does not include personal information with third parties for industry analysis and other purposes.</p>
<h4>Cookies</h4>
<p>We use "cookies" to collect information. Cookies are data files that our site or third party service providers transfer to your computer's hard drive through your web browser that enables our Platform to recognize your browser and capture and remember certain information. This will enable us to remember your logging information and recognize you in future logins. Furthermore, cookies may allow us to better understand how you and other users interact with the Platform. Third party advertisers and/or service providers may also place or read cookies on your browser. You can change your browser's preferences to stop accepting cookies or to notify you before accepting a cookie from the websites you visit. If you do not accept cookies, however, you may not be able to use all features of our Platform.</p>
<h4>Email address and phone number</h4>
<p>As part of our service, Gloobers users may choose to communicate (via email or phone). Once you upload email address, Gloobers will use it only to send you mails from other users. If you upload a phone number, Gloobers will not disclose it to other users until a reservation is confirmed, but may use it to contact you over the phone to connect you with the other users.</p>
<h4>Identity theft</h4>
<p>Safeguarding information to help protect you from identity theft is very important to us. We will not, at any time, request your credit card information, your Gloobers Account ID, login password, ID number or passport number in a non-secure manner.</p>
<h4>Information Sharing and Disclosure</h4>
<p>When you create your account, your profile page will display your First name. You can select the other items of Personal Information that you wish to be included in your account profile page - including, but not limited to, a profile picture and links to your Listings. This information will be displayed to other users on your Gloobers profile page and with your permission on third party sites. You can review and revise your settings at any time. Additionally, listings posted by service providers, ratings and reviews of service providers and guests and the Profile Information of service providers and guests, are publicly displayed to all Gloobers users.</p>
<h4>Listings</h4>
<p>If you, as service providers, post a listing, we may publish that listing through the Platform and may enable third parties to publish your listing on their sites. We may also display the geographical location of your listing on a map, but your actual street address will not be disclosed unless you reach a confirmed booking with a guest.
If you, as guest, request a booking, we will share your personal information with the relevant professional/host. This information will enable the host to decide whether to confirm or reject your booking. Once the booking is confirmed. We will share relevant information about the service providers with you.</p>
<h4>Service Providers</h4>
<p>We may employ third party companies and individuals to provide certain services on our behalf or for us. Such third parties may have access to your personal information and in such case it will be accessible to them only for the purpose of performing their task and they will be obligated not to disclose or use it for any other purpose. We may also provide Personal Information to our business partners or other trusted entities for the purpose of providing you with information on goods or services we believe will be of interest to you. You can, at any time, opt out of receiving such communications. Such third parties may use cookies and you can disable these specific cookies.</p>
<h4>Compliance</h4>
<p>Gloobers may disclose any information about you to government or law enforcement officials where Gloobers believes, at its sole discretion, that it is necessary in order to (a) comply with the law (b) it is appropriate to respond to claims and legal processes (c) enforce our policies (d) protect the rights related third parties or other Gloobers users (e) to prevent any activity that we may consider to be illegal, unethical or legally actionable activity.</p>
<h4>Change of ownership</h4>
<p>Gloobers may sell, transfer or otherwise share part or all of its assets, including your personal information, in connection with a merger, acquisition, reorganization or sale of assets or in the event of bankruptcy.</p>
<h4>Changing or Deleting your account</h4>
<p>You may, at any time, change or delete part or all of your information and/or profile. Unless we have a legal obligation or a legitimate business reason to retain the information contained in your account. Some of the information you upload to the site (e.g. reviews) may stay publicly displayed after you delete/cancel your account.</p>
<h4>Security</h4>
<p>We implement a variety of security measures to maintain the safety of your personal information when you place an order. When you enter sensitive information, such as your credit card details, that information is encrypted and transmitted via Secure Socket Layer (SSL) technology. We do our best to use generally accepted industry standards and technology, however, we cannot guarantee full security over the internet.</p>
<h4>Links to Other Websites</h4>
<p>Our Platform may offer links to other sites and service providers. This does not mean that Gloobers endorse those sites, their services or their Privacy Policies and Terms of Use. Should you choose to click on such links or banners or otherwise, it is advisable that you read their policies.</p>
<h4>Children</h4>
<p>We are in compliance with the requirements of COPPA (Childrens Online Privacy Protection Act). Our Platform is not intended to individuals under 18. We do not knowingly collect information from children under 13. If a parent or guardian becomes aware that his or her child has provided us with any information without their consent, he or she should contact us. If we become aware that a child under 13 has provided us with any information, we will delete it.</p>
<h4>Contacting Us</h4>
<p>If you have any questions about this Privacy Policy, please contact us at <b>contact@gloobers.com</b></p>
</div>
</div>